#!/usr/bin/env bash
set -Eeuo pipefail
AUDIT=${1:-$(pwd)}; SRC=${2:-/home/audit/audit/ivxv}; OUT="$AUDIT/evidence/source-audit"
mkdir -p "$OUT"/command-logs "$OUT"/test-results "$OUT"/static-analysis "$OUT"/fuzzing "$OUT"/code-maps
printf 'timestamp_utc\t%s\nsource\t%s\ncommit\t%s\n' "$(date -u +%FT%TZ)" "$SRC" "$(git -C "$SRC" rev-parse HEAD)" > "$OUT/source-state.tsv"
{ printf 'component\tlanguage\tprimary_executable\tsecurity_role\tfiles_reviewed\trelevant_tests\taudit_status\treviewer_notes\tlinked_findings\tlinked_leads\n';
 for d in choices common/collector core mid proxy sessionstatus smartid storage verification voting webeid processor auditor collector-admin key; do
   [ -d "$SRC/$d" ] || continue; lang=Go; case "$d" in processor|auditor|key) lang=Java;; collector-admin) lang=Python;; esac
   printf '%s\t%s\t%s\t%s\t%s\t%s\tnot-started\tautomated preliminary inventory only; substantive review required\t\t\n' "$d" "$lang" "$d" 'security-sensitive component' "$d/**" "$d/**/*_test*"
 done; } | sort -t $'\t' -k1,1 > "$OUT/review-coverage.tsv"
{ printf 'component\tpath\tsymbol_or_entry\tinterface\ttrust_boundary\tevidence\n';
 rg -l 'func main\(\)|public static void main|def [a-zA-Z_]+\(' "$SRC" --glob '*.go' --glob '*.java' --glob '*.py' | sort | while read -r f; do printf '%s\t%s\t%s\tlocal executable or service\tprocess/network boundary\t%s\n' "$(basename "$f")" "${f#$SRC/}" "entry point" "${f#$SRC/}"; done; } > "$OUT/entry-points.tsv"
printf 'flow_id\tfrom\tto\tdata\tsecurity_property\tsource\nF1\tvoter authentication\tcollector\tsigned ballot/container\tauthenticity and eligibility\tcommon/collector; webeid; smartid\nF2\tcollector\tstorage\tidentified ballot\tdurability and acknowledgement\tcommon/collector; storage\nF3\tprocessor\tanonymizer\taccepted ballots and revocation lists\tlatest vote and paper cancellation\tprocessor/src/main/java/ee/ivxv/processor/tool\nF4\tanonymizer\tauditor/decrypt\tanonymous ballot box\tidentity separation and proof verification\tprocessor; auditor\n' > "$OUT/data-flow-inventory.tsv"
printf 'boundary\towner\tinput\tassumption\tevidence\nTB1\tcollector\tidentity provider and signed container\tupstream authentication and PKI trusted\tcommon/collector; webeid; smartid\nTB2\tstorage\tservice API\tetcd endpoint and filesystem protected\tstorage/service/storage/main.go:295\nTB3\tprocessor\tballot box and revocation lists\toffline inputs authentic and complete\tprocessor/src/main/java/ee/ivxv/processor/tool\nTB4\tauditor\tproofs/manifests\texternally supplied files authentic\tauditor/src/main/java/ee/ivxv/audit/tools\n' > "$OUT/trust-boundaries.tsv"
printf 'property\tinvariant\tsource\ttest_or_evidence\tstatus\nballot conservation\taccepted = retained + superseded + rejected\tprocessor/src/main/java/ee/ivxv/processor\tno dedicated audit test\tuntested\nidentity separation\tanonymous output omits voter identifier and linkage\tprocessor/.../BallotBox.java; RevokeAndAnonymizeTool.java\tstatic trace\tneeds targeted fixture\nrevote ordering\tlatest qualified ballot selected per voter\tprocessor/.../BallotBox.java\tunit tests present\treviewed\nrevocation idempotence\trepeated revoke/restore does not alter unrelated voter\tprocessor/.../RevokeTool.java\tno dedicated test\tuntested\n' > "$OUT/vote-lifecycle-invariants.tsv"
printf 'target\tlanguage\tentry\tinput\tcommand\tresult\tlimitations\ncollector-zip\tGo\tcommon/collector/zip\tZIP/container\tgo test ./common/collector/zip\tnot-run\tfixtures/toolchain\ncommand-file\tPython\tcollector-admin/ivxv_admin/command_file.py\tBDOC/YAML\tstatic review\tmanual review\tno signed fixture\nprocessor-tools\tJava\tprocessor tools\tballot box\tGradle test\tNO-SOURCE\tmissing fixtures\n' > "$OUT/fuzz-targets.tsv"
printf 'target\tresult\tevidence\tnotes\nGo modules\tPhase 3 reconstruction tests executed\t../test-results/reconstructed/go-module-results.tsv\treconstruction only\nJava tests\tGradle NO-SOURCE/SKIPPED\t../command-logs/phase3-toolchain-recon-test-java.txt\tno test methods executed\n' > "$OUT/security-property-test-map.tsv"
